# Key Bindings
# key name refer to `xev` or `wev` command output, 
# mod keys name: super,ctrl,alt,shift,none

# reload config
bind=SUPER,r,reload_config

# menu and terminal
bind=Alt,space,spawn,rofi -config ~/.config/maomao/rofi/config.rasi -show drun
bind=SUPER,Return,spawn,wezterm

# app bind
bind=SUPER+SHIFT,s,spawn,sh ~/.config/maomao/scripts/screenshot.sh
bind=SUPER,l,spawn,swaylock -f -c 000000

# exit
bind=SUPER,m,quit
bind=SUPER,c,killclient,

# switch window focus
bind=SUPER,Tab,focusstack,next
bind=SUPER,h,focusdir,left
bind=SUPER,i,focusdir,right
bind=SUPER,e,focusdir,up
bind=SUPER,n,focusdir,down

# swap window
bind=SUPER+SHIFT,e,exchange_client,up
bind=SUPER+SHIFT,n,exchange_client,down
bind=SUPER+SHIFT,h,exchange_client,left
bind=SUPER+SHIFT,i,exchange_client,right

# switch window status
bind=SUPER,g,toggleglobal,
bind=ALT,Tab,toggleoverview,
bind=ALT,backslash,togglefloating,
bind=ALT,a,togglemaxmizescreen,
bind=ALT,f,togglefullscreen,
bind=ALT+SHIFT,f,togglefakefullscreen,
# bind=SUPER,l,minized,
bind=SUPER,o,toggleoverlay,
# bind=SUPER+SHIFT,L,restore_minized
bind=ALT,z,toggle_scratchpad

# scroller layout
bind=ALT,e,set_proportion,1.0
bind=ALT,x,switch_proportion_preset,

# switch layout
bind=SUPER,k,switch_layout

# tag switch
bind=SUPER,Left,viewtoleft,
bind=SUPER+CTRL,h,viewtoleft,
# bind=SUPER+CTRL,h,viewtoleft_have_client,
bind=SUPER,Right,viewtoright,
bind=SUPER+CTRL,i,viewtoright,
# bind=SUPER+CTRL,i,viewtoright_have_client,
bind=CTRL+SUPER,Left,tagtoleft,
bind=CTRL+SUPER,Right,tagtoright,

bind=SUPER,1,view,1
bind=SUPER,2,view,2
bind=SUPER,3,view,3
bind=SUPER,4,view,4
bind=SUPER,5,view,5
bind=SUPER,6,view,6
bind=SUPER,7,view,7
bind=SUPER,8,view,8
bind=SUPER,9,view,9

# tag: move client to the tag and focus it
# tagsilent: move client to the tag and not focus it
# bind=Alt,1,tagsilent,1
bind=Alt,1,tag,1
bind=Alt,2,tag,2
bind=Alt,3,tag,3
bind=Alt,4,tag,4
bind=Alt,5,tag,5
bind=Alt,6,tag,6
bind=Alt,7,tag,7
bind=Alt,8,tag,8
bind=Alt,9,tag,9

# monitor switch
bind=ALT+SHIFT,h,focusmon,left
bind=ALT+SHIFT,i,focusmon,right
bind=SUPER+ALT,h,tagmon,left
bind=SUPER+ALT,i,tagmon,right

# gaps
bind=ALT+SHIFT,X,incgaps,1
bind=ALT+SHIFT,Z,incgaps,-1
bind=ALT+SHIFT,R,togglegaps

# movewin
bind=CTRL+SHIFT,e,movewin,+0,-50
bind=CTRL+SHIFT,n,movewin,+0,+50
bind=CTRL+SHIFT,h,movewin,-50,+0
bind=CTRL+SHIFT,i,movewin,+50,+0

# resizewin
bind=CTRL+ALT,e,resizewin,+0,-50
bind=CTRL+ALT,n,resizewin,+0,+50
bind=CTRL+ALT,h,resizewin,-50,+0
bind=CTRL+ALT,i,resizewin,+50,+0

# Mouse Button Bindings
# NONE mode key only work in ov mode
mousebind=SUPER,btn_left,moveresize,curmove
# mousebind=NONE,btn_middle,togglemaxmizescreen,0
mousebind=SUPER,btn_right,moveresize,curresize
mousebind=NONE,btn_left,toggleoverview,-1
mousebind=NONE,btn_right,killclient,0

# Axis Bindings
axisbind=SUPER,UP,viewtoleft_have_client
axisbind=SUPER,DOWN,viewtoright_have_client
